#LED
set_property PACKAGE_PIN AG14      [get_ports "led_pins[0]"]  
set_property IOSTANDARD  LVCMOS33  [get_ports "led_pins[0]"]  
set_property PACKAGE_PIN AF13      [get_ports "led_pins[1]"]  
set_property IOSTANDARD  LVCMOS33  [get_ports "led_pins[1]"]  
set_property PACKAGE_PIN AE13      [get_ports "led_pins[2]"]  
set_property IOSTANDARD  LVCMOS33  [get_ports "led_pins[2]"]  
set_property PACKAGE_PIN AJ14      [get_ports "led_pins[3]"]  
set_property IOSTANDARD  LVCMOS33  [get_ports "led_pins[3]"]  
set_property PACKAGE_PIN AJ15      [get_ports "led_pins[4]"]  
set_property IOSTANDARD  LVCMOS33  [get_ports "led_pins[4]"]  
set_property PACKAGE_PIN AH13      [get_ports "led_pins[5]"]  
set_property IOSTANDARD  LVCMOS33  [get_ports "led_pins[5]"]
set_property PACKAGE_PIN AH14      [get_ports "led_pins[6]"]  
set_property IOSTANDARD  LVCMOS33  [get_ports "led_pins[6]"]  
set_property PACKAGE_PIN AL12      [get_ports "led_pins[7]"]  
set_property IOSTANDARD  LVCMOS33  [get_ports "led_pins[7]"]

set_output_delay -clock clk0 -1 [get_ports {led_pins[*]}]