// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package hyper_pad_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 0;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic        q;
    } smt;
    struct packed {
      logic        q;
    } slw;
    struct packed {
      logic [1:0]  q;
    } drv;
  } hyper_pad_reg2hw_pads_reg_t;

  // Register -> HW type
  typedef struct packed {
    hyper_pad_reg2hw_pads_reg_t pads; // [3:0]
  } hyper_pad_reg2hw_t;

  // Register offsets
  parameter logic [BlockAw-1:0] HYPER_PAD_PADS_OFFSET = 0'h 0;

  // Register index
  typedef enum int {
    HYPER_PAD_PADS
  } hyper_pad_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] HYPER_PAD_PERMIT [1] = '{
    4'b 0001  // index[0] HYPER_PAD_PADS
  };

endpackage

