add wave -position 0  sim:/hyperbus_tb/axi_i/clk_i
add wave -position 1  sim:/hyperbus_tb/axi_i/aw_id
add wave -position 2  sim:/hyperbus_tb/axi_i/aw_addr
add wave -position 3  sim:/hyperbus_tb/axi_i/aw_len
add wave -position 4  sim:/hyperbus_tb/axi_i/aw_size
add wave -position 5  sim:/hyperbus_tb/axi_i/aw_burst
add wave -position 6  sim:/hyperbus_tb/axi_i/aw_lock
add wave -position 7  sim:/hyperbus_tb/axi_i/aw_cache
add wave -position 8  sim:/hyperbus_tb/axi_i/aw_prot
add wave -position 9  sim:/hyperbus_tb/axi_i/aw_qos
add wave -position 10  sim:/hyperbus_tb/axi_i/aw_region
add wave -position 11  sim:/hyperbus_tb/axi_i/aw_user
add wave -position 12  sim:/hyperbus_tb/axi_i/aw_valid
add wave -position 13  sim:/hyperbus_tb/axi_i/aw_ready
add wave -position 14  sim:/hyperbus_tb/axi_i/w_data
add wave -position 15  sim:/hyperbus_tb/axi_i/w_strb
add wave -position 16  sim:/hyperbus_tb/axi_i/w_last
add wave -position 17  sim:/hyperbus_tb/axi_i/w_user
add wave -position 18  sim:/hyperbus_tb/axi_i/w_valid
add wave -position 19  sim:/hyperbus_tb/axi_i/w_ready
add wave -position 20  sim:/hyperbus_tb/axi_i/b_id
add wave -position 21  sim:/hyperbus_tb/axi_i/b_resp
add wave -position 22  sim:/hyperbus_tb/axi_i/b_user
add wave -position 23  sim:/hyperbus_tb/axi_i/b_valid
add wave -position 24  sim:/hyperbus_tb/axi_i/b_ready
add wave -position end  sim:/hyperbus_tb/dut_i/i_cdc_RX_fifo/src_rst_ni
add wave -position end  sim:/hyperbus_tb/dut_i/i_cdc_RX_fifo/src_clk_i
add wave -position end  sim:/hyperbus_tb/dut_i/i_cdc_RX_fifo/src_data_i
add wave -position end  sim:/hyperbus_tb/dut_i/i_cdc_RX_fifo/src_valid_i
add wave -position end  sim:/hyperbus_tb/dut_i/i_cdc_RX_fifo/src_ready_o
add wave -position end  sim:/hyperbus_tb/dut_i/i_cdc_RX_fifo/dst_rst_ni
add wave -position end  sim:/hyperbus_tb/dut_i/i_cdc_RX_fifo/dst_clk_i
add wave -position end  sim:/hyperbus_tb/dut_i/i_cdc_RX_fifo/dst_data_o
add wave -position end  sim:/hyperbus_tb/dut_i/i_cdc_RX_fifo/dst_valid_o
add wave -position end  sim:/hyperbus_tb/dut_i/i_cdc_RX_fifo/dst_ready_i
add wave -position 20  sim:/hyperbus_tb/dut_i/hyperbus_phy_i/trans_valid_i
add wave -position 21  sim:/hyperbus_tb/dut_i/hyperbus_phy_i/trans_ready_o
add wave -position 22  sim:/hyperbus_tb/dut_i/hyperbus_phy_i/trans_address_i
add wave -position 23  sim:/hyperbus_tb/dut_i/hyperbus_phy_i/trans_cs_i
add wave -position 24  sim:/hyperbus_tb/dut_i/hyperbus_phy_i/trans_write_i
add wave -position 25  sim:/hyperbus_tb/dut_i/hyperbus_phy_i/trans_burst_i
add wave -position 26  sim:/hyperbus_tb/dut_i/hyperbus_phy_i/trans_burst_type_i
add wave -position 27  sim:/hyperbus_tb/dut_i/hyperbus_phy_i/trans_address_space_i
add wave -position 28  sim:/hyperbus_tb/dut_i/hyperbus_phy_i/trans_error_o
add wave -position 29  sim:/hyperbus_tb/dut_i/hyperbus_phy_i/tx_valid_i
add wave -position 30  sim:/hyperbus_tb/dut_i/hyperbus_phy_i/tx_ready_o
add wave -position 31  sim:/hyperbus_tb/dut_i/hyperbus_phy_i/tx_data_i
add wave -position 32  sim:/hyperbus_tb/dut_i/hyperbus_phy_i/tx_strb_i
add wave -position 33  sim:/hyperbus_tb/dut_i/hyperbus_phy_i/rx_valid_o
add wave -position 34  sim:/hyperbus_tb/dut_i/hyperbus_phy_i/rx_ready_i
add wave -position 35  sim:/hyperbus_tb/dut_i/hyperbus_phy_i/rx_data_o
add wave -position 21  sim:/hyperbus_tb/dut_i/hyper_axi_state
add wave -position 38  sim:/hyperbus_tb/dut_i/hyperbus_phy_i/hyper_trans_state